FROM rockylinux:8

ENV container docker

# Install systemd -- See https://hub.docker.com/_/centos/
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# dnf update
RUN dnf -y update

# Install Nginx
RUN dnf -y install nginx && \
    systemctl enable nginx

# Install PHP
RUN dnf -y module reset php && \
    dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm && \
    dnf -y module enable php:remi-8.2 && \
    dnf -y install php

# Install PHP Modules
RUN dnf -y install php-mysqli php-mbstring php-pdo php-gd php-fpm php-json php-bcmath php-zip php-redis libjpeg* libpng* freetype* gd-* gcc gcc-c++ gdbm-devel libtermcap-devel && \
    systemctl enable php-fpm

# Install PHP PECL & Redis
# 이전에는 php-redis 모듈을 설치하기 위해 pecl을 설치하고, pecl로 모듈을 설치하는 방식이었으나
# 현재 dnf로 설치가 가능하다.
# RUN dnf -y install php-pear php-devel make && \
#     pecl install redis && \
#     echo "extension=redis" > /etc/php.d/20-redis.ini

# Install PHP Composer
RUN cd /tmp && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

# php session dir permission change
RUN chown root:nginx /var/lib/php/session

# Custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Custom nginx default config
COPY cache.conf /etc/nginx/default.d/cache.conf
COPY error.conf /etc/nginx/default.d/error.conf
COPY php.conf /etc/nginx/default.d/php.conf

# Rewrite php-fpm config
RUN sed -i 's/user = apache/user = nginx/g' /etc/php-fpm.d/www.conf && \
    sed -i 's/group = apache/group = nginx/g' /etc/php-fpm.d/www.conf && \
    sed -i 's/;listen.owner = nobody/listen.owner = nginx/g' /etc/php-fpm.d/www.conf && \
    sed -i 's/;listen.group = nobody/listen.group = nginx/g' /etc/php-fpm.d/www.conf && \
    sed -i 's/listen = \/run\/php-fpm\/www.sock/listen = 127.0.0.1:9000/g' /etc/php-fpm.d/www.conf && \
    sed -i 's/php_value\[session.save_handler\] = files/php_value\[session.save_handler\] = redis/g' /etc/php-fpm.d/www.conf && \
    sed -i 's/php_value\[session.save_path\]    = \/var\/lib\/php\/session/php_value\[session.save_path\]    = \"tcp\:\/\/redis\:6379\"/g' /etc/php-fpm.d/www.conf

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
